on:
  issue_comment:
    types: [created]
name: Commented Pull Request
jobs:
  pullRequestHandler:
    name: PullRequestHandler
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a
      - name: PullRequestHandler
        uses: ScoopInstaller/GithubActions@a709983c0692a8a853c288cf5e9bf14658107936
        if: startsWith(github.event.comment.body, '/verify')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
